#version: '3'

services:
#
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
#    volumes:
#      - .:/usr/src/app
  postgres:
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data


volumes:
  postgres: