// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type Translation struct {
	ID           string `json:"id"`
	Abbreviation string `json:"abbreviation"`
	Version      string `json:"version"`
}
